# Generated by Django 5.2.12 on 2026-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Enter skills separated by commas')),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0–1 Years'), ('1-2', '1–2 Years'), ('2-3', '2–3 Years'), ('3+', '3+ Years')], max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
